---
- hosts: docker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: stop all docker containers
    shell: docker stop $(docker ps -q)
  - name: delete all docker containers
    shell: docker rm $(docker ps -aq)
  - name: uninstall docker-engine
    apt: pkg=docker-engine state=absent purge=yes
