--- # Step one of the roles lab
- hosts: prod
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
  tasks:
    - name: Validate Group exists
      group: name=ciss state=present

    - name: Validate CISS users
      user: name={{ item }} shell=/bin/bash state=present group=ciss
      with_items:
      - david
      - ritesh
      - travis
      - kelly

    - name: Validate packages
      apt: name={{ item }} state=installed
      with_items: 
      - ssh
      - telnet
      notify: restart ssh
     
    - name: Validate Services
      service: name={{ item }} state=running
      with_items:
      - ssh


  handlers:

  - name: restart ssh
    service: name=ssh state=restarted
