--- # This is the run once playbook example
- hosts: all
  user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /home/ubuntu/uptime.log
    - name: List the /var directory and log it
      raw: ls -al /var >> /home/ubuntu/dir.list
      run_once: true
