--- # This is a local action playbook 
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  tasks:
   - name: Install Apache Utilities
     apt: pkg=apache2-utils state=latest

