--- # Install OpenStack from script
- hosts: openstack
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no

  tasks: 

  - name: Copy RDO from script
    copy: src=/ubuntu/rdo-install.sh dest=/home/ubuntu/ owner=ubuntu group=ubuntu mode=0777

  - name: Execute RDO install script
    command: sh /home/ubuntu/rdo-install.sh

