--- # Tag functionality example
- hosts: appservers
  user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the telnet and lynx packages
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages 
    - name: Verify telnet is installed
      raw: yum list installed | grep telnet > /home/ubuntu/pkg.log
      tags:
        - always


