--- # update etc/hosts on all machines
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks: 
   - name: copy local /etc/hosts to all ansible servers
     copy: src=/etc/hosts dest=/etc/hosts owner=root group=root mode=0644 force=yes
   - name: copy local known_hosts
     copy: src=/home/ubuntu/.ssh/known_hosts dest=/home/ubuntu/.ssh/known_hosts owner=ubuntu group=ubuntu mode=0644 force=yes
   - name: copy public ssh_key to remote ansible hosts
     copy: src=/home/ubuntu/.ssh/id_rsa.pub dest=/home/ubuntu/.ssh/id_rsa.pub owner=ubuntu group=ubuntu mode=0644 force=yes
   - name: copy ssh_key to remote ansible hosts
     copy: src=/home/ubuntu/.ssh/id_rsa dest=/home/ubuntu/.ssh/id_rsa owner=ubuntu group=ubuntu mode=0600 force=yes
