--- # Lookup Playbook Example
- hosts: appservers
  user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  
  tasks:
   - debug: msg="{{ lookup('env','HOME') }} is the value listed"
