---
- hosts: localhost
  remote_user: ubuntu
  connection: local
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
  tasks:
    - name: Install tree
      apt: name=tree state=present

    - name: Install jq
      apt: name=jq state=present

    - name: Install pip
      apt: name={{ item }} state=present
      with_items:
      - python-pip
      - python-dev
      - build-essential
    - name: Install passlib
      pip: name=passlib

