--- # This will publish some webpages to wordpress
- hosts: wp-pb-ap
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
    - name: Install WordPress Themes
      command: wp theme install {{ item }} --allow-root chdir=/var/www/html
      with_items:
         - bluebiz
         - lifelog
         - indreams
         - start
         - lightword

    - name: Updating PHP header
      blockinfile:
         dest: /var/www/html/wp-content/themes/bluebiz/header.php
         insertafter: <div class="site-branding">
         content: |
            <p class="site-description"><?php echo "I am hosted by {{ ansible_hostname }} with an IP of {{ ansible_ens3.ipv4.address }}.";?></p>

    - name: Updating PHP header
      blockinfile:
         dest: /var/www/html/wp-content/themes/lifelog/header.php
         insertafter: <div class="site-branding">
         content: |
            <p class="site-description"><?php echo "I am hosted by {{ ansible_hostname }} with an IP of {{ ansible_ens3.ipv4.address }}.";?></p>

    - name: Updating PHP header
      blockinfile:
         dest: /var/www/html/wp-content/themes/indreams/header.php
         insertafter: <div class="site-branding">
         content: |
            <p class="site-description"><?php echo "I am hosted by {{ ansible_hostname }} with an IP of {{ ansible_ens3.ipv4.address }}.";?></p>

    - name: Updating PHP header
      blockinfile:
         dest: /var/www/html/wp-content/themes/start/header.php
         insertafter: <div class="site-branding">
         content: |
            <p class="site-description"><?php echo "I am hosted by {{ ansible_hostname }} with an IP of {{ ansible_ens3.ipv4.address }}.";?></p>

    - name: Updating PHP header
      blockinfile:
         dest: /var/www/html/wp-content/themes/lightword/header.php
         insertafter: <div class="site-branding">
         content: |
            <p class="site-description"><?php echo "I am hosted by {{ ansible_hostname }} with an IP of {{ ansible_ens3.ipv4.address }}.";?></p>


