---
- hosts: wp-pb-db
  become: yes
  become_method: sudo
  connection: ssh 
  vars:
    wp_mysql_db: MyWP
    wp_mysql_user: wpUser
    wp_mysql_password: wpP4ss
    mysql_root_user: root
    mysql_root_password: Passw0rd
  tasks:
    - name: Add repo file
      template: src=mariadb.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644
      register: mariadb_list

    - name: Add repo key
      apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present
      register: mariadb_key

    - name: Update all packages
      apt: upgrade=dist update_cache=yes

    - name: Unattended package installation
      shell: export DEBIAN_FRONTEND=noninteractive
      changed_when: false

    - name: Install needed packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
          - vim-nox
          - apache2
          - mariadb-server
          - mariadb-client
          - php5
          - php5-mysql
          - python-mysqldb

    - name: Enable remote MySQL access
      lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address = 0.0.0.0"

    - name: Set MariaDB Root Password
      command: mysqladmin -u root PASSWORD Passw0rd

    - name: Create Remote user account
      shell: mysql -u root -p'Passw0rd' -e "CREATE USER 'root'@'192.168.10.151' IDENTIFIED BY 'Passw0rd';"

    - name: Provide Privileges
      shell: mysql -u root -p'Passw0rd' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.10.151';"

    - name: Flush Privileges
      shell: mysql -u root -p'Passw0rd' -e "FLUSH PRIVILEGES;"

    - name: Set root password
      mysql_user: name=root password=Passw0rd host=* priv=*.*:ALL,GRANT state=present
      ignore_errors: true

    - name: Set access for remote host
      mysql_user: name=root password=Passw0rd host=192.168.10.151 priv=*.*:ALL,GRANT state=present

    - name: Copy ~/.my.cnf to nodes
      template: src=my.cnf.j2 dest=/root/.my.cnf

    - name: Create MariaDB database
      mysql_db: name={{ wp_mysql_db }} state=present

    - name: Create MariaDB username and password
      mysql_user:
          login_user={{ mysql_root_user }}
          login_password={{ mysql_root_password }}
          name={{ wp_mysql_user }}
          host=192.168.10.151
          password={{ wp_mysql_password }}
          priv=*.*:ALL

    - name: Ensure MariaDB is running (and enable it at boot)
      service: name=mysql state=restarted enabled=yes
