---
- hosts: wp-pb-db
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: removee mysql-server
    apt: pkg={{ item }} state=absent purge=yes
    with_items:
    - mysql-server
    - mysql-common
    - mysql-client

