--- # docker things
- hosts: docker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks: 
   - name: start nginx container
     docker: name=nginx image=nginx state=started
