---
# Install Ansible 
- hosts: docker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
  tasks:
    - name: Validate the Ansible PPA
      apt_repository: repo='ppa:ansible/ansible'

    - name: Validate Ansible is installed
      apt: name=ansible state=installed update_cache=yes

# Install Docker
- hosts: docker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install pre-reqs
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
      - apt-transport-https
      - ca-certificates
      - python-pip
    - name: Installing Docker-Py
      pip: name={{ item }} state=latest
      with_items:
      - docker-py
    - name: Add GPG key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
    - name: Create docker.list file
      raw: touch /etc/apt/sources.list.d/docker.list
    - name: Add repo
      raw: echo 'deb https://apt.dockerproject.org/repo ubuntu-{{ansible_lsb.codename}} main' > /etc/apt/sources.list.d/docker.list
    - name: Install Docker Engine
      apt: pkg=docker-engine state=latest update_cache=true
    - name: Start Docker Service
      service: name=docker state=started
    - name: add user to docker group
      user: name=ubuntu group=docker append=yes
    - name: run container hello-world
      docker: name=hello-world image=hello-world state=started 

# docker things
- hosts: docker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks: 
   - name: start cadvisor container
     docker:
          name: cadvisor
          image: google/cadvisor:latest
          ports:
          - "8080:8080"
          volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          privileged: yes
          state: started
   - name: start wordpress all-in-ine
     docker: 
          name: wordpressaio
          image: s5atrain/wordpress:aio
          ports: "8082:8080"
          state: started

#docker run -d -P --name wpaio s5atrain/wordpress:aio

#docker run --detach=true --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --privileged=true --name=cadvisor google/cadvisor:latest
