---
# this playbook copies /etc/hosts from acs and places it in remote ~
- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no
 
  tasks:
  - name: copy /etc/hosts file from acs to remote machines
    copy: src=/etc/hosts dest=/home/ubuntu/tmp owner=ubuntu group=ubuntu mode=0644

