---
# Lookup ini
- hosts: wp-dev
  remote_user: ubuntu
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no
 
  tasks:
  - debug: msg="User in integration is {{ lookup('ini', 'user section=integration file=users.ini') }}"
  - debug: msg="User in production  is {{ lookup('ini', 'user section=production  file=users.ini') }}"
