--- # This is the master playbook for appservers
- hosts: module04
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  pre_tasks: 
  - name: when did the role start to run
    raw: date > /home/ubuntu/startofrole.log
  roles: 
    - databases
  post_tasks:
  - name: when did the role stop running
    raw: date > /home/ubuntu/stopofrole.log
