--- # Playbook demonstration and use of the authorize_key module
    # link: http://docs.ansible.com/ansible/authorized_key_module.html
    # This playbook adds the SSH authorized key for particular user accounts

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  tasks:

  - name: install ssh key
    authorized_key: user=ansible
                    key="{{lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
                    state=present
