---
- hosts: wp-pb-db
  become: yes
  become_method: sudo
  connection: ssh 
  vars:
    wp_mysql_db: MyWP
    wp_mysql_user: wpUser
    wp_mysql_password: wpP4ss
    mysql_root_user: root
    mysql_root_password: Passw0rd
  tasks:
    - name: Create Remote user account
      shell: mysql -u root -p'Passw0rd' -e "CREATE USER 'root'@'192.168.10.153' IDENTIFIED BY 'Passw0rd';"

    - name: Provide Privileges
      shell: mysql -u root -p'Passw0rd' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.10.153';"

    - name: Flush Privileges
      shell: mysql -u root -p'Passw0rd' -e "FLUSH PRIVILEGES;"

