---
- hosts: wp-ro-ha
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    wp_mysql_db: MyWP
    wp_mysql_user: wpUser
    wp_mysql_password: wpP4ss
    mysql_root_user: root
    mysql_root_password: Passw0rd
  tasks:
#    - name: Update all packages
#      apt: upgrade=dist update_cache=yes
    - name: Install Git
      apt: pkg=git state=installed 

    - name: Unattended package installation
      shell: export DEBIAN_FRONTEND=noninteractive
      changed_when: false

    - name: Install needed packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
          - vim-nox
          - apache2
          - mysql-client
          - php5
          - php5-mysql
          - python-mysqldb

    - name: Is WP-CLI downloaded?
      stat: path="/usr/local/bin/wp"
      register: wpcli_is_downloaded

    - name: Download WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: 0655
      when: wpcli_is_downloaded.stat.exists == False

    - name: Make WP-CLI executable
      file:
        path: /usr/local/bin/wp
        mode: u=rwx,g=rx,o=rx
      when: wpcli_is_downloaded.stat.exists == False

    - name: Is WordPress downloaded?
      stat: path=/var/www/html/index.php
      register: wordpress_is_downloaded

    - name: Download WordPress
      shell: /usr/local/bin/wp core download --allow-root
      args:
        chdir: /var/www/html

      when: wordpress_is_downloaded.stat.exists == False

    - name: Configure WordPress
      shell: /usr/local/bin/wp core config --allow-root
                --path=/var/www/html
                --dbhost="192.168.10.156"
                --dbname="{{ wp_mysql_db }}"
                --dbuser="{{ mysql_root_user }}"
                --dbpass="{{ mysql_root_password }}"
      when: wordpress_is_downloaded.stat.exists == False
