--- # Create a Playbook from an Outline (take 2)
- hosts: appservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
   - name: create time stamp
     raw: /usr/bin/date > /home/ubuntu/start_time.log
   - name: install httpd, lynx, telnet
     yum: pkg={{ item }} state=latest
     with_items:
       - httpd
       - lynx
       - telnet
   - name: output all installed packages
     shell: yum list installed > /home/ubuntu/installed_pkgs.log
   - name: create time stamp
     raw: /usr/bin/date > /home/ubuntu/end_time.log

